schema_version: 1

context:
  python_min: 3.11
  version: "1.1.2"

package:
  name: dirac-cwl
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/dirac-cwl/dirac_cwl-${{ version }}.tar.gz
  sha256: da94f0381c49d3697136864855ccab4b9cd4b95774491303be1f5ab3a8188599

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - dirac-cwl = dirac_cwl:app
      - crypto = dirac_cwl.modules.crypto:app
      - pi-simulate = dirac_cwl.modules.pi_simulate:app
      - pi-gather = dirac_cwl.modules.pi_gather:app

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=42
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >=${{ python_min }}
    - cwl-utils
    - cwlformat
    - cwltool
    - dirac-grid >=9.0.0
    - diracx-api
    - lbprodrun
    - mypy
    - pydantic
    - pyyaml
    - typer
    - referencing >=0.30
    - rich
    - ruamel.yaml

tests:
  - python:
      imports:
        - dirac_cwl
      pip_check: true
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - dirac-cwl --help
      - crypto --help
      - pi-simulate --help
      - pi-gather --help

about:
  summary: Prototype of CWL used as a production/job workflow language for DIRAC
  license: GPL-3.0-only
  license_file: LICENSE
  homepage: https://pypi.org/project/dirac-cwl/

extra:
  recipe-maintainers:
    - aldbr
    - ryuwd
